module.exports = [
	"Software Developer",
	"Data Scientist",
	"Digital Marketer",
	"Product Manager",
	"UX/UI Designer",
	"Financial Analyst",
	"Sales Representative",
	"Customer Service Representative",
	"Healthcare Worker",
	"Teacher/Educator",
	"Civil Engineer",
	"Mechanical Engineer",
	"Electrical Engineer",
	"Project Manager",
	"Human Resources Specialist",
	"Cybersecurity Specialist",
	"Accountant",
	"Marketing Manager",
	"Graphic Designer",
	"Architect",
	"Social Media Manager",
	"Business Analyst",
	"Supply Chain Manager",
	"IT Support Specialist",
	"AI/ML Engineer",
	"Legal Advisor",
	"Content Writer",
	"Biomedical Engineer",
	"Environmental Scientist",
	"Construction Manager",
	"Other"
];
